---
title: "National_summary"
output: html_document
---

```{r setup, include=FALSE}
library(cancensus)
library(knitr)
library(RPostgreSQL)
library(sf)
library(tidyverse)

source("../Can_BICS_OSM_functions.R")
source("../personal_paths_and_variables.R") # cancensus api key

# stats can lambert
target_projection <- 3347

central_db_name <- "Can_BICS_provinces"

# 1. Get population and area from census
census_data <- get_census(dataset='CA16', regions=list(PR=c("60","61","59","48","47","46","62","35","24","10","13","12","11")), vectors=c("v_CA16_401","v_CA16_5792","v_CA16_5807"), labels="detailed", geo_format='sf', level='CSD') %>%
  st_transform(target_projection)

# first, make the name match the stats can shapefile
census_data$short_name <- str_replace(census_data$name, " \\s*\\([^\\)]+\\)", "")

# select important variables, shorten names
census_data_rename <- census_data %>%
  dplyr::select(name = short_name,
         CSDUID = GeoUID,
         Dwellings,
         Population = `v_CA16_401: Population, 2016`,
         Area = `Area (sq km)`,
         Commuters = `v_CA16_5792: Total - Main mode of commuting for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data`,
         Bike_Commuters = `v_CA16_5807: Bicycle`,
         geometry)

census_data_rename$size <- base::cut(census_data_rename$Population,
                          breaks = c(-1, 50000, 500000, Inf),
                          labels = c("small", "medium", "large"))
census_data_rename$Bicycle_Mode_Share <- round(100 * census_data_rename$Bike_Commuters /
  census_data_rename$Commuters, 1)

highways_output <- st_read("../../data/national/OSM_CAN_BICS.shp")

highways_output$length <- st_length(highways_output) %>% as.numeric()

infra_levels <- c("Bike Path",
                  "Cycle Track",
                  "Local Street Bikeway",
                  "Multi-Use Path",
                  "Painted Bike Lane",
                  "Non-Conforming")

recode_ground_data_predicted <- function(Can_BICS){
    Can_BICS_recode = recode(Can_BICS,
  "Cycle Track (on roadway)" = "Cycle Track",
  "Non-Conforming Major Road" = "Non-Conforming",
  "Non-Conforming Trail" = "Non-Conforming",
  "Non-Conforming Other" = "Non-Conforming", 
  "None" = "Non-Conforming") %>%
      replace_na("Non-Conforming")
  Can_BICS_recode <- factor(Can_BICS_recode,
                            levels = infra_levels)
  return(Can_BICS_recode)
}

highways_output$Can_BICS_recode <- recode_ground_data_predicted(highways_output$CBICS_infr) %>% as.character()

non_conforming <- c("Non-conforming major road",
                                     "Non-conforming other",
                                     "Non-conforming trail",
                    "Non-conforming",
                    "Non-Conforming",
                    NA,
                    "None",
                    "Substandard")

summary_Can_BICS <- highways_output %>%
  st_drop_geometry() %>%
  #filter(! Can_BICS %in% non_conforming) %>%
  group_by(Can_BICS_recode) %>%
  summarise(length = sum(length)/1000 %>% round(0)) %>%
  mutate(percentage = (length / sum(length)) * 100 %>%
           round(0)) %>%
  mutate(length = round(length, 0),
         percentage = round(percentage, 1))

summary_Can_BICS[nrow(summary_Can_BICS) + 1, ] <- NA
summary_Can_BICS[nrow(summary_Can_BICS), ]$Can_BICS_recode <- "Total"

summary_Can_BICS[nrow(summary_Can_BICS), ]$length <- sum(summary_Can_BICS$length, na.rm = T)

summary_Can_BICS[nrow(summary_Can_BICS), ]$percentage <- sum(summary_Can_BICS$percentage, na.rm = T)

row.names(summary_Can_BICS) <- summary_Can_BICS$Can_BICS_recode

summary_Can_BICS <- summary_Can_BICS[c(infra_levels,
                                       "Total"),]

summary_Can_BICS_class <- highways_output %>%
  st_drop_geometry() %>%
  filter(! CBICS_comf %in% non_conforming) %>%
  group_by(CBICS_comf) %>%
  summarise(length = sum(length)/1000 %>% round(0)) %>%
  mutate(percentage = (length / sum(length)) * 100 %>%
           round(0)) %>%
  mutate(length = round(length, 0),
         percentage = round(percentage, 0))

total <- sum(summary_Can_BICS_class$length)
total_Can_BICS <- sum(summary_Can_BICS_class[which(! summary_Can_BICS_class$C_BICS_ %in% "Non-conforming"), ]$length)
  
total_non_conforming <- sum(highways_output[which( highways_output$C_BICS_ %in% "Non-Conforming"), ]$length) / 1000
```

## National summary
```{r}
kable(summary_Can_BICS,
      caption = "National, by infrastructure type.")

kable(summary_Can_BICS_class,
      caption = "National, by comfort class.")

print(paste0("Total infrastructure: ", total))
print(paste0("Total Can-BICS: ", total_Can_BICS))

print(paste0("Total non-conforming infrastructure: ", total_non_conforming))

```

``` {r, echo = F, warning = F}
# Box Plot
# highways_output <- st_intersection(highways_output,
#                                    csds)

# summarize infrastructure by type and city
prediction_infratype_city <- get_lengths_proportions_groups(
  highways_output,
  highways_output$Can_BICS_recode %>% Can_BICS_class(),
  highways_output$CSDUID)

prediction_infratype_city <- prediction_infratype_city %>%
  left_join(census_data_rename, by = c("Group" = "CSDUID")) %>%
  filter(Population > 5000)


prediction_infratype_city$Can_BICS_class <- prediction_infratype_city$Category %>% 
  as.factor()

# metrics
prediction_infratype_city$km_per_100k <- (prediction_infratype_city$Length / (prediction_infratype_city$Population / 100000))

prediction_infratype_city$km_per_km2 <- prediction_infratype_city$Length / (prediction_infratype_city$Area)

# log transform
prediction_infratype_city$km_per_100k_log10 <- log10(prediction_infratype_city$km_per_100k)
prediction_infratype_city$km_per_100k_log10[which(prediction_infratype_city$km_per_100k_log10 < 0)] <- 0

# get the max for each group
prediction_infratype_city <- prediction_infratype_city %>%
  group_by(Can_BICS_class, size) %>%
  mutate(max_group = km_per_100k == max(km_per_100k),
         max_label = ifelse(max_group, 
                            paste0(name, " (", round(km_per_100k, 0)," km/100k)"), 
                            NA))

# get the min for each group
prediction_infratype_city <- prediction_infratype_city %>%
  group_by(Can_BICS_class, size) %>%
  mutate(min_group = km_per_100k == min(km_per_100k),
         min_label = ifelse(min_group, 
                            paste0(name, " (", round(km_per_100k, 0)," km/100k)"), 
                            NA))

# multiple zeros for small
prediction_infratype_city$min_label[which(prediction_infratype_city$size %in% "small" &
                                            prediction_infratype_city$Length == 0)] <- NA

# assign one label for eacy comfort class
multiple_zero_text <- "Multiple (0 km/100k)"
prediction_infratype_city$min_label[which(prediction_infratype_city$size %in% "small" &
                                            prediction_infratype_city$Can_BICS_class %in% "1. High Comfort" & 
                                            prediction_infratype_city$name %in% "Wilmot")] <- multiple_zero_text

prediction_infratype_city$min_label[which(prediction_infratype_city$size %in% "small" &
                                            prediction_infratype_city$Can_BICS_class %in% "2. Medium Comfort" & 
                                            prediction_infratype_city$name %in% "Paradise")] <- multiple_zero_text

prediction_infratype_city$min_label[which(prediction_infratype_city$size %in% "small" &
                                            prediction_infratype_city$Can_BICS_class %in% "3. Low Comfort" & 
                                            prediction_infratype_city$name %in% "Perth East")] <- multiple_zero_text

prediction_infratype_city$min_label[which(prediction_infratype_city$size %in% "small" &
                                            prediction_infratype_city$Can_BICS_class %in% "Non-Conforming" & 
                                            prediction_infratype_city$name %in% "West Hants")] <- multiple_zero_text


Can_BICS_colours <- c(
  "#9C9C9C", # non_conforming: grey
  "#73B2FF", # low: blue
  "#89CD66", # med: light green
  "#267300") # high: dark green

prediction_infratype_city %>%
  ggplot( aes(x = size, 
              y = km_per_100k_log10,#Proportion * 100, 
              fill = fct_rev(Can_BICS_class))) +
    geom_boxplot() +
    scale_fill_manual(values = Can_BICS_colours) +
    scale_y_continuous(limits = c(-5, 9)) +
    # geom_jitter(color = "black",
    #             size = 0.6,
    #             alpha = 0.9,
    #             height = 0.5) +
    theme_minimal() +
    theme(
      plot.title = element_text(size=11)
    ) +
    guides(fill = guide_legend(reverse = TRUE)) +
    ggtitle("Bicycle facilities in all census subdivisions") +
    xlab("") +
    ylab("log10(km / 100,000 population)") +
    labs(fill = "Can-BICS Comfort Class") +
    geom_text(aes(label = max_label),
              na.rm = TRUE,
              position = position_dodge(width = .76),
              hjust = "left",
              vjust = "middle",
              size = 2.5) +
      geom_text(aes(label = min_label),
              na.rm = TRUE,
              position = position_dodge(width = 0.76),
              hjust = "right",
              vjust = "middle",
              size = 2.5) +
  coord_flip()


  
```

``` {r, echo = F, warning = F}
# get sample cities CSDUID
sample_cities_csds <- c("1209034", "1301006", "2443027", 
                        "2466023", "3501012", "3506008", 
                        "4611040", "4706027", "4811061",
                        "4815023", "5915022", "5917034", 
                        "5926010", "5931020", "6001009")

# Ridge Plot
library(ggridges)
prediction_infratype_city %>%
  ggplot(aes(
    y=fct_rev(Can_BICS_class), 
    # x = Proportion * 100,
    # x = km_per_100k,
    x = km_per_100k_log10, 
    fill=Can_BICS_class)) +
  scale_fill_manual(values = rev(Can_BICS_colours)) +
  geom_density_ridges(alpha = 0.6,
                      scale = 2.5,
                      jittered_points = T,
                      position = position_points_jitter(width = 0.05, 
                                                        height = 0),
                      point_shape = '|', 
                      point_size = 1, point_alpha = 1) +
  theme_ridges() +
  theme(axis.text.y=element_blank()) +
  scale_x_continuous(limits = c(0, 4),
                     labels = c("0", "10", "100", "1,000", "10,000")) +
  ylab("") + 
  xlab("km / 100,000 population") +
  labs(fill = "Can-BICS Comfort Class") +
  facet_wrap(~fct_rev(size),
             nrow = 3,
             strip.position = "left",
             scales = "fixed")

  ggsave("../../figures/ridges_national.pdf")

prediction_infratype_city %>%
  filter(Group %in% sample_cities_csds) %>%
  ggplot(aes(
    y=fct_rev(Can_BICS_class), 
    #x=Proportion * 100,
    # x=(km_per_100k),
    x = (km_per_100k_log10), 
    fill=Can_BICS_class)) +
  scale_fill_manual(values = rev(Can_BICS_colours)) +
  geom_density_ridges(alpha = 0.6,
                      scale = 2.5,
                      jittered_points = T,
                      position = position_points_jitter(width = 0.05, 
                                                        height = 0),
                      point_shape = '|', 
                      point_size = 5, point_alpha = 1) +
  theme_ridges() +
  theme(axis.text.y=element_blank()) +
  scale_x_continuous(limits = c(0, 4),
                     labels = c("0", "10", "100", "1,000", "10,000")) +
  ylab("") + 
  xlab("km / 100,000 population") +
  labs(fill = "Can-BICS Comfort Class") +
  facet_wrap(~fct_rev(size),
             nrow = 3,
             strip.position = "left",
             scales = "fixed")

  ggsave("../../figures/ridges_sample.pdf")


```

```{r}
#Individual city summary for face validation session

### Whitehorse
summary_Can_BICS_whitehorse_class <- highways_output %>%
  filter(CSDNAME %in% "Whitehorse") %>%
  st_drop_geometry() %>%
  filter(! CBICS_comf %in% non_conforming) %>%
  group_by(CBICS_comf) %>%
  summarise(length = sum(length)/1000 %>% round(0)) %>%
  mutate(percentage = (length / sum(length)) * 100 %>%
           round(0)) %>%
  mutate(length = round(length, 0),
         percentage = round(percentage, 0))

highways_output %>%
  filter(CSDNAME %in% "Whitehorse") %>% 
  View()

total_non_conforming_whitehorse <- sum(highways_output[which(highways_output$CSDNAME %in% "Whitehorse" &
                                                        highways_output$CBICS_comf %in% non_conforming), ]$length)


kable(summary_Can_BICS_whitehorse_class,
      caption = "Whitehorse, by comfort class.")
print(paste0("Total non-conforming infrastructure: ", total_non_conforming_whitehorse))

```